### PR TITLE
Replace string concatenation method

### LINKED ISSUE #598: Try += for string concatenation
Summary: 

Paul Ganssle's recent article showed that using `+=` rather than `''.join` can be faster for string concatenation in Python. https://blog.ganssle.io/articles/2019/11/string-concat.html

For lots of the SQL generation in Django-MySQL I suspect this also holds and could be a nice little improvement.

### PR DESCRIPTION
**Pull request by opeerator**
Fixes #598 

Summary:

Using `+=` rather than `.join` can be faster for string concatenation in Python, according to [this article](https://blog.ganssle.io/articles/2019/11/string-concat.html).

Solution:

replacing all of the `.join` methods in the src folder to `+=` for string concatenation.

### CODE REVIEW

**Comment by adamchainz** [comment]
This issue was a bit of a "note to self" and a suspicion, not a fact. Did you time any of the instances you changed?

**Comment by opeerator** [comment]
Oh, I see. I thought we might have a similar behavior like the article mentions here as well. I'm trying to time some of the instances, but it does not always favor concat or join concretely.

**Comment by adamchainz** [comment]
I'd like to see concrete numbers from `%timeit` on ipython before merging any change.

**Comment by opeerator** [comment]
Here you go, yeah it doesn't seem much of an improvement in every case. In cases that we have `.format()`, `.join` seems a better option. :/

[time_modules.pdf](https://github.com/adamchainz/django-mysql/files/5680064/time_modules.pdf)

**Comment by adamchainz** [comment]
Thanks for this. Yeah I don't think any of the cases are significant enough to warrant a change here.

It's likely there are similar paths in Django that can be optimized the same way, and they'd have higher impact since it's much more popular. Perhaps you could go hunting there? We're more interested in saving microseconds there since they multiply out to a bigger scale.

Also check out [djangobench](https://github.com/django/djangobench) which is Django's performance benchmarking suite, currently undergoing some improvement work.

**Pull request closed without merging**
