### PR TITLE
Test on Python 3.5

### PR DESCRIPTION
**Pull request by graingert**
replaces #175

### CODE REVIEW

**Comment by adamchainz** [comment]
Looks like Django 1.7 itself won't work with 3.5:

```
  File "/home/travis/build/adamchainz/django-mysql/.tox/py35-django17/lib/python3.5/site-packages/django/utils/html.py", line 16, in <module>
    from .html_parser import HTMLParser, HTMLParseError
```

:cry: 

Also pytest seems broken:

```
.tox/py35-django18/lib/python3.5/site-packages/_pytest/assertion/rewrite.py:700: in visit_Name
    locs = ast.Call(self.builtin("locals"), [], [], None, None)
E   TypeError: Call constructor takes either 0 or 3 positional arguments
_________________ ERROR collecting tests/testapp/test_cache.py _________________
```

**Comment by adamchainz** [comment]
Merged in 0b917557120a15df903c0e4150868ee241cfbdec

**Comment by graingert** [comment]
*gong*

**Comment by adamchainz** [comment]
You didn't add yourself to CONTRIBUTORS, feel free to open a PR doing so if you wish to appear.

**Comment by graingert** [comment]
there's always https://github.com/adamchainz/django-mysql/graphs/contributors

**Pull request closed without merging**
