### PR TITLE
Add JSONArrayAppend database function.

### PR DESCRIPTION
**Pull request by arnau126**
Summary:
`JSONArrayAppend` is a DB function that appends values to the end of the indicated arrays within a JSON document.
(https://dev.mysql.com/doc/refman/5.7/en/json-modification-functions.html#function_json-array-append)

Checklist:

- [x] Line added to HISTORY.rst
- [x] Test added to `test_functions:JSONFunctionTests`

### CODE REVIEW

**Comment by adamchainz** [comment]
Thanks. Please add docs too :)

**Comment by arnau126** [comment]
Which type of doc? I don't see any other json func documented.

**Comment by adamchainz** [comment]
They're all doc'd at https://django-mysql.readthedocs.io/en/latest/database_functions.html#json-database-functions / https://github.com/adamchainz/django-mysql/blob/master/docs/database_functions.rst#json-database-functions

**Comment by arnau126** [comment]
I amended my previous commit with the function doc.

**Comment by adamchainz** [comment]
Released in version 2.4.0 https://pypi.org/project/django-mysql/2.4.0/

**Pull request merged**
