### PR TITLE
Fix set fields’ contains lookup

### PR DESCRIPTION
**Pull request by tuky**
This should be obvious enough to merge and ship quickly, I hope. Thx!

### CODE REVIEW

**Comment by tuky** [comment]
Funny enough this bug should be 8 years old now and only emerged for us with django 4.1. I assume they refactored / reordered some query building logic and with that query parts got split into lhs and rhs.

**Comment by adamchainz** [comment]
Please add a regression test and a release note.

**Comment by tuky** [comment]
ah, great stuff with the auto fixing :) :+1:

**Comment by adamchainz** [comment]
I wrote a simpler test that checked the lookup directly on the field, and copied it between the two field variants. Also changed release note to document things at the level of the project (the set fields) rather than the underlying SQL funciton name (kind of an implementation detail).

**Comment by adamchainz** [comment]
Released in 4.8.0, thanks!

**Comment by tuky** [comment]
thx a lot!

**Pull request merged**
