### PR TITLE
Add TimestampField

### PR DESCRIPTION
**Pull request by adamchainz**
Todo
- [ ] Basic tests
- [ ] `DEFAULT CURRENT_TIMESTAMP`, `ON UPDATE CURRENT_TIMESTAMP`
- [ ] Migration tests
- [ ] Docs
- [ ] Release note

### CODE REVIEW

**Comment by adamchainz** [comment]
I don't think this is worth it

**Comment by StevenMapes** [comment]
May I ask why you didn't think this was worth it? If you are using a database that can be written to from outside of django then being ale to add this in may be a requirement to allow those other sources records to work as the database engineer intended.

I've actually had this for clients where I have ported existing databases into django, managed to convince them to allow me to manage them from within django but where they still writin records from outside of the python project. In this case I have created a new new subclass of DatetTimeField directly within the project and overloaded the db_type method to set these up checking the connection type was MySQL/MariaDB first of all

```
class DateTimeWithDefaultAndUpdateCurrentTimeStampField(models.DateTimeField):
    """DateTimeField Extension to add in CURRENT_TIMESTAMP default behaviour"""
    def db_type(self, connection):
        if connection.vendor == "mysql":
            typ = ['DATETIME']
            typ += ['default CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()']
            return ' '.join(typ)
        else:
            return super(DateTimeWithDefaultAndUpdateCurrentTimeStampField, self).db_type(connection)


class DateTimeDefaultCurrentTimeStampField(models.DateTimeField):
    """DateTimeField Extension to add in CURRENT_TIMESTAMP default behaviour"""
    def db_type(self, connection):
        if connection.vendor == "mysql":
            typ = ['DATETIME']
            typ += ['default CURRENT_TIMESTAMP()']
            return ' '.join(typ)
        else:
            return super(DateTimeDefaultCurrentTimeStampField, self).db_type(connection)
```

**Comment by adamchainz** [comment]
Maybe it would be worth it

**Comment by adamchainz** [comment]
I don't have time to work on this. If there was a PR for a complete implementaiton, sure I'd review and merge it. This PR can serve as a starting point.

**Pull request closed without merging**
