### PR TITLE
Include latest stable Python into the test run

### PR DESCRIPTION
**Pull request by Toshakins**
It's a draft pull request. I open it to check if tests will run on Python 3.7 fine.

### CODE REVIEW

**Comment by Toshakins** [comment]
Sorry, I thought Travis would test PR by default :( I will do all needed checks offline.

Again sorry for the hassle and opening an incorrect PR.

**Comment by adamchainz** [comment]
I have a plan to test on Python 3.7 myself so no need to do the work yourself

**Comment by Toshakins** [comment]
Thanks for the answer! By the way, I found that one of the projects I involved in successfully uses 3.5.

Again sorry for opening PR without the compliance with CONTRIBUTING guide.

**Comment by adamchainz** [comment]
Yeah technically I aim to support Python 3.4+, I don't have testing there but generally the changes between Python versions are small enough that I'd realize if code was using something not in 3.4. Plus if there was a bug report from an untested Python, I'd fix that. When moving to test with Python 3.7 I aim to revisit this.

**Pull request closed without merging**
